### ISSUE TITLE
this.material is null

### ISSUE THREAD

**Issue by aesopcmc** [Mooy1/InfinityExpansion#121]
Error Generated: 2023-07-02-05-02

Java Environment:
  Operating System: Linux
  Java Version: 17.0.7

Server Software: Paper
  Build: git-Paper-375 (MC: 1.19.3)
  Minecraft v1.19.3-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun v2023.06-release
  Caused by: InfinityExpansion vBuild 7 zh-CN(SlimefunGuguProject) (git 00b37e0)

Installed Addons (5)
  + GuizhanLibPlugin Build 27 (git c731e3d)
  + InfinityExpansion Build 7 zh-CN(SlimefunGuguProject) (git 00b37e0)
  + CMILib 1.2.4.5
  + Residence 5.1.0.1
  + SlimeGlue 1.0.2-0543427

Installed Plugins (60):
  + PlaceholderAPI 2.11.2
  + JoinMessagePlus 4.0
  + Boom 1.3.3
  + LiftReloaded 2.4.1
  + HolographicDisplays 3.0.1-SNAPSHOT-b243
  + ConsoleSpamFix 1.10.0
  + CommandTimer 8.3.0
  + DeluxeTags 1.8.2-Release
  + EpicPluginLib 2.3
  + PlayMoreSounds 4.2
  + MiniMOTD 2.0.10
  + LuckPerms 5.4.58
  + CrazyAuctionsPlus 1.3.2.1
  + WorldBorder 1.9.10 (beta)
  + ProtocolLib 5.0.0-SNAPSHOT-b608
  + LiteSignIn 1.7.0.0
  + Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
  + Chunky 1.3.92
  + NametagEdit 4.5.14
  + SkinsRestorer 14.2.5
  + Orebfuscator 5.4.0
  + NexEngine 2.2.10 build-15/06/2023
  + WorldEdit 7.2.13+46576cc
  + VentureChat 3.4.3
  + Essentials 2.20.0
  + InteractiveChat 4.2.5.5
  + AutoMessager 3.1
  + RedPacket 1.5.5
  + Citizens 2.0.30-SNAPSHOT (build 2890)
  + ExcellentCrates 4.3.2
  + TimeIsMoney 1.9.6.22
  + MoneyHunters 7.0.7 Basic
  + PlayerParticles 8.3
  + ExcellentEnchants 3.4.3
  + InteractionVisualizer 1.18.4.0
  + PlotSquared 6.11.0
  + PlayerPoints 3.2.5
  + EssentialsSpawn 2.20.0
  + CoreProtect 21.3
  + TitleManager 2.3.6
  + Multiverse-Core 4.3.1-b861
  + TrMenu 3.1.17
  + mcMMO 2.1.219-SNAPSHOT
  + AutoResetWorld 2.5
  + EliteMobs 8.5.4
  + AuthMe 5.6.0-SNAPSHOT-b2573
  + LockettePro 2.12.2
  + Slimefun 2023.06-release
  + PvPManager 3.10.9
  + GuizhanLibPlugin Build 27 (git c731e3d)
  + MarriageMaster 2.6.10-Release
  + McMmoView 1.0.2
  + InfinityExpansion Build 7 zh-CN(SlimefunGuguProject) (git 00b37e0)
  + CMILib 1.2.4.5
  + Residence 5.1.0.1
  + QuickShop 5.1.1.2
  + SlimeGlue 1.0.2-0543427
  + StackMob 5.8.7
  + MyPet 3.12
  + PlugManX 2.3.3

Block Info:
  World: world
  X: 9814
  Y: 100
  Z: 8851
  Material: ACACIA_WOOD
  Block Data: org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftRotatable
  State: org.bukkit.craftbukkit.v1_19_R2.block.CraftBlockState

Ticker-Info:
  Type: Synchronized

Slimefun Data:
  ID: REINFORCED_STORAGE
  Is data loaded: true
  Inventory: true
  Data: 
    stored: 12312

Stacktrace:

java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.getMaxStackSize()" because "this.material" is null
	at [粘液科技扩展-无尽]InfinityExpansion-Build 5 zh-CN(SlimefunGuguProject) (git 018bfe1).jar//io.github.mooy1.infinityexpansion.items.storage.StorageCache.output(StorageCache.java:340)
	at [粘液科技扩展-无尽]InfinityExpansion-Build 5 zh-CN(SlimefunGuguProject) (git 018bfe1).jar//io.github.mooy1.infinityexpansion.items.storage.StorageCache.tick(StorageCache.java:351)
	at [粘液科技扩展-无尽]InfinityExpansion-Build 5 zh-CN(SlimefunGuguProject) (git 018bfe1).jar//io.github.mooy1.infinityexpansion.items.storage.StorageUnit$1.tick(StorageUnit.java:106)
	at Slimefun-v2023.06-release.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:167)
	at Slimefun-v2023.06-release.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:148)
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Boomer-1** [comment]
this is not from the official version of infinity expansion. this is the chinese fork. please close this and report to the proper github

**Comment by Takeoff0518** [comment]
> this is not from the official version of infinity expansion. this is the chinese fork. please close this and report to the proper github

however, it seems that the official version has the same exception. 

see #130
