### ISSUE TITLE
storage dupe

### ISSUE THREAD

**Issue by FakEEE14** [Mooy1/InfinityExpansion#61]
https://vimeo.com/546431161

[15:15:40 ERROR]: [InfinityExpansion] Item "INFINITY_STORAGE" from InfinityExpansion vDEV - 103 (git 765f00a7) has caused an Error!
[15:15:40 ERROR]: [InfinityExpansion] You can report it here: https://github.com/Mooy1/InfinityExpansion/issues
[15:15:40 ERROR]: [InfinityExpansion] Could not pass "BlockBreakHandler" for StorageUnit - 'INFINITY_STORAGE' (InfinityExpansion vDEV - 103 (git 765f00a7))
java.lang.NullPointerException: null
        at io.github.mooy1.infinityexpansion.implementation.storage.StorageUnit.onBreak(StorageUnit.java:182) ~[?:?]
        at io.github.mooy1.infinityexpansion.infinitylib.slimefun.abstracts.AbstractContainer$2.onPlayerBreak(AbstractContainer.java:67) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callBlockHandler$2(BlockListener.java:157) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.callItemHandler(SlimefunItem.java:953) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:157) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:125) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor340.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-641]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-641]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-641]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:359) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:259) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1636) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1391) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-641]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-641]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Mooy1** [comment]
fixed in latest build
