### ISSUE TITLE
CS-CoreLib breaks this plugin?

### ISSUE THREAD

**Issue by gphg** [Mooy1/InfinityExpansion#64]
## Description (Required)

The InfinityExpansion recipe on Slimefun's main menu isn't accessible. It shows, but it unable to access the item. Sometime when quits the menu, the SF book can't be accessed.

On console, shows the error bellow on Server Log.

## Steps to reproduce the Issue (Required)

1. Get Slimefun4 and this plugin installed.
2. It works as it.
3. Get [CS-CoreLib](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/) plugin installed.
4. An error occurred (see Description)

## Expected behavior (Required)

It said it's required as written on [this wiki page](https://github.com/Mooy1/InfinityExpansion/wiki/How-to-make-a-Slimefun-Server), but on my first test drive I didn't get it installed because it doesn't show on latest version of both Slimefun4 and InfinityExpansion build pages.

This happened because I was planning to installed other plugins and it required CS-CoreLib. This happened today, I've been played this for 3 days on new world. I figured it by removed plugins one-by-one.

## Server Log / Error Report

```
[20:56:04 ERROR]: Could not pass event InventoryClickEvent to Slimefun vDEV - 916 (git e4225d7a)
java.lang.LinkageError: loader constraint violation: loader (instance of org/bukkit/plugin/java/PluginClassLoader) previously initiated loading for a different type with name "me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu"
	at io.github.mooy1.infinityexpansion.infinitylib.slimefun.utils.MultiCategory.openGuide(MultiCategory.java:57) ~[?:?]
	at io.github.mooy1.infinityexpansion.infinitylib.slimefun.utils.MultiCategory.open(MultiCategory.java:51) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.openCategory(SurvivalSlimefunGuide.java:230) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.lambda$displayCategory$4(SurvivalSlimefunGuide.java:199) ~[?:?]
	at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor10.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-706]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-706]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-706]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:619) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2706) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1330) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-706]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[20:56:06 ERROR]: Could not pass event InventoryClickEvent to Slimefun vDEV - 916 (git e4225d7a)
java.lang.LinkageError: loader constraint violation: loader (instance of org/bukkit/plugin/java/PluginClassLoader) previously initiated loading for a different type with name "me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu"
	at io.github.mooy1.infinityexpansion.infinitylib.slimefun.utils.MultiCategory.openGuide(MultiCategory.java:57) ~[?:?]
	at io.github.mooy1.infinityexpansion.infinitylib.slimefun.utils.MultiCategory.open(MultiCategory.java:51) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.openCategory(SurvivalSlimefunGuide.java:230) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.lambda$displayCategory$4(SurvivalSlimefunGuide.java:199) ~[?:?]
	at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor10.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-706]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-706]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-706]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:619) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2706) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1330) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[patched_1.16.5.jar:git-Paper-706]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-706]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
```

## Environment (Required)

 - Minecraft Version: 1.16.5
 - Slimefun Version: DEV - 916 (git e4225d7a)
 - Plugin Version: DEV - 111 (git 461a3fd6)

**Comment by Mooy1** [comment]
Ah I need to update that page, you no longer need CS-CoreLib

**Comment by Mooy1** [comment]
None of the actively developed addons need it either, so you can remove it.
